version: 2.1

commands:
  setup:
    steps:
    - checkout
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
    - run:
        name: Install dependencies
        command: |
            opam repo -a add coq-extra-dev https://coq.inria.fr/opam/extra-dev
            opam update
            opam pin remove dune -n
            opam install --deps-only .
    - run:
        name: List installed packages
        command: opam list

defaults: &defaults
  environment:
    OPAMBESTEFFORT: true
    OPAMJOBS: 2
    OPAMVERBOSE: 1
    OPAMWITHTEST: true
    OPAMYES: true
    TERM: xterm
  resource_class: medium
  steps:
  - setup
  - run:
      name: Build, test, and install package
      command: opam install .
  - run:
      name: Uninstall package
      command: opam remove .

jobs:
  test:
    parameters:
      coq:
        type: string
    docker:
    - image: coqorg/coq:<<parameters.coq>>
    <<: *defaults

  test-with-make:
    parameters:
      coq:
        type: string
    docker:
    - image: coqorg/coq:<<parameters.coq>>
    <<: *defaults
    steps:
    - setup
    - run:
        name: Build, test
        command: make all
    - run:
        name: Clean
        command: make clean

workflows:
  version: 2
  build:
    jobs:
    - test:
        name: "Coq 8.13"
        coq: "8.13"
    - test:
        name: "Coq 8.14"
        coq: "8.14"
    - test:
        name: "Coq 8.15"
        coq: "8.15"
    - test:
        name: "Coq 8.16"
        coq: "8.16"
    - test:
        name: "Coq 8.17"
        coq: "8.17"
    - test:
        name: "Coq 8.18"
        coq: "8.18"
    - test:
        name: "Coq 8.19"
        coq: "8.19"
    - test:
        name: "Coq 8.20"
        coq: "8.20"
    - test:
        name: "Coq dev"
        coq: "dev-ocaml-4.13-flambda"
    - test-with-make:
        name: "Coq 8.17 + make"
        coq: "8.17"
